# -------------------------------------------
# Quick Container Tabs - project properties
# -------------------------------------------
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1024M

# Mod base info
mod_id=qct
mod_name=Quick Container Tabs
mod_version=0.1.0-beta-1.21.1
mod_group_id=com.south13oy.qct
mod_authors=South13OY
mod_license=MIT

# Target environment
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.250
loader_version_range=[21.1,)
# NeoGradle 2.0 userdev plugin version
neogradle_version=7.1.38
